Gerenciamento_Restaurante/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('controle_pedidos.urls'))
]

controle_pedidos/urls.py
from django.urls import path
from . import views

app_name = 'controle_pedidos'
urlpatterns = [
    path('', views.Login, name="login"),
    path('idcomanda', views.IDComanda, name="idcomanda"),
    path('logout', views.Logout, name='logout'),
    path('menu', views.Menu, name='menu'),
    path('idcomanda/<int:id>', views.DetalhesPedido, name='detalhespedido'),
    path('novopedido/<int:id>', views.NovoPedido, name='novopedido'),
    path('idcomandagerencia/<int:id>', views.DetalhesGerencia, name='detalhespedidogerencia'),
    path('gerenciaprodutos', views.GerenciaProdutos, name='gerenciaprodutos'),
    path('gerenciaprodutos/detalhes/<int:id>', views.DetalhesProduto, name='detalhesproduto'),
    path('gerenciaprodutos/adicionar', views.AdicionarProduto, name='adicionarproduto'),
    path('listapedidos', views.ListaPedidos, name='listapedidos'),
    path('gerenciaprodutos/deletar/<int:id>', views.DeletarProduto, name='deletarproduto'),
    path('menu/cadastraratendente', views.CadastrarAtendente, name='cadastraratendente'),
]

controle_pedidos/models.py
from django.db import models
from datetime import date

# Create your models here.
class Produto(models.Model):
    nome = models.CharField(max_length=100)
    valor_unitario = models.DecimalField(default=0, max_digits=7, decimal_places=2)
    descricao = models.CharField(max_length=200)

    def cod_produto(self):
        return self.pk

    def __str__(self):
        return self.nome

class Pedido(models.Model):
    cod_comanda = models.PositiveSmallIntegerField(default=0, primary_key=True)
    valor_total = models.DecimalField(default=0, max_digits=7, decimal_places=2)
    pago = models.BooleanField(default=False)
    data = models.DateField(default=date.today)
    cod_mesa = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return ("Código da Comanda:"+str(self.cod_comanda))

class ItensPedido(models.Model):
    cod_pedido = models.PositiveSmallIntegerField(default=0)
    cod_produto = models.PositiveSmallIntegerField(default=0)
    quantidade = models.SmallIntegerField(default=0)

    def __str__(self):
        return ("Cod_Pedido:"+str(self.cod_pedido)+" Produto:"+str(self.cod_produto)+", Qnt:"+str(self.quantidade))

controle_pedidos/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group
from .models import Produto, Pedido, ItensPedido



def Login(request):
    context ={}
    # Confirmação de usuário para o Navbar
    if request.user.is_authenticated:
        context['usuariologado'] = 'Logado como: ' + request.user.get_short_name()
        if (request.user.has_perm('controle_pedidos.delete_pedido')):
            return redirect(reverse('controle_pedidos:menu', ), context)
        else:
            return redirect(reverse('controle_pedidos:idcomanda', ), context)
    else:
        context['usuariologado'] = 'Deslogado'

    try:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if (request.user.has_perm('controle_pedidos.delete_pedido')):
                return redirect(reverse('controle_pedidos:menu', ), context)
            else:
                return redirect(reverse('controle_pedidos:idcomanda', ), context)

        else:
            context['erro'] = 'Usuário/Senha errada!'
            return render(request,'controle_pedidos/login.html', context)

    except(KeyError):
        return render(request, 'controle_pedidos/login.html', context)

def Logout(request):
    context = {}
    if request.user.is_authenticated:
        context['usuariologado'] = 'Logado como: ' + request.user.get_short_name()
    else:
        context['usuariologado'] = 'Deslogado'


    logout(request)
    return redirect(reverse('controle_pedidos:login', ), context)

def IDComanda(request):
    context = {}
    # Confirmação de usuário para o Navbar
    if request.user.is_authenticated:
        context['usuariologado'] = 'Logado como: ' + request.user.get_short_name()
        if (request.user.has_perm('controle_pedidos.delete_pedido')):
            context['perm']= 'True'
            perm = True
        else:
            context['perm'] = 'False'
            perm = False
    else:
        context['usuariologado'] = 'Deslogado'
        return redirect(reverse('controle_pedidos:login', ), context)

    try:
        idcomanda = request.POST['idcomanda']
        context['idpedido'] = int(idcomanda)
        try:
            #Se houver algum pedido com este código:
            if(Pedido.objects.filter(cod_comanda=idcomanda).count()!=0):
                if(perm):
                    return redirect(reverse('controle_pedidos:detalhespedidogerencia', args=(idcomanda,)),context)

                return redirect(reverse('controle_pedidos:detalhespedido', args=(idcomanda,)), context)

            #Se não houver pedido com este código
            else:
                context['erro'] = 'Não há comanda registrada com este ID!'
                if(perm):
                    context['perm'] = 'True'
                return render(request, 'controle_pedidos/idcomanda.html', context)
        except:
            return render(request, 'controle_pedidos/idcomanda.html', context)

    # Campo vazio, continuar na página
    except:
        return render(request, 'controle_pedidos/idcomanda.html', context)

def Menu(request):
    context = {}
    # Confirmação de usuário para o Navbar
    if request.user.is_authenticated:
        context['usuariologado'] = 'Logado como: ' + request.user.get_short_name()
        if (not request.user.has_perm('controle_pedidos.delete_pedido')):
            return redirect(reverse('controle_pedidos:idcomanda', ), context)
    else:
        context['usuariologado'] = 'Deslogado'
        return redirect(reverse('controle_pedidos:login', ), context)



    return render(request,'controle_pedidos/menu.html', context)

def DetalhesPedido(request, id):
    context = {}
    context['id'] = id


    # Confirmação de usuário para o Navbar
    if request.user.is_authenticated:
        context['usuariologado'] = 'Logado como: ' + request.user.get_short_name()
        if (request.user.has_perm('controle_pedidos.delete_pedido')):
            return redirect(reverse('controle_pedidos:menu', ), context)
    else:
        context['usuariologado'] = 'Deslogado'
        return redirect(reverse('controle_pedidos:login', ), context)

    # Listagem dos produtos para a tabela
    produtos = ItensPedido.objects.filter(cod_pedido=id)
    listaprodutos = []
    listavalores = []
    listaqnt = []
    for p in produtos:
        if(p.quantidade>0):
            listaprodutos.append(Produto.objects.get(pk=p.cod_produto).nome)
            listavalores.append(Produto.objects.get(pk=p.cod_produto).valor_unitario)
            listaqnt.append(p.quantidade)

    context['lista'] = tuple(zip(*(listaprodutos, listavalores, listaqnt)))

    valor_total = 0
    for indice, valor in enumerate(listavalores):
        valor_total+= valor*listaqnt[indice]

    Pedido.objects.filter(cod_comanda=id).update(valor_total=valor_total)
    context['valor_total'] = Pedido.objects.get(cod_comanda=id).valor_total

    listatodosprods = []

    for tp in Produto.objects.all():
        listatodosprods.append(tp)


    context['TodosProdutos'] = listatodosprods
    context['mesa'] = Pedido.objects.get(cod_comanda=id).cod_mesa
    context['pago'] = Pedido.objects.get(cod_comanda=id).pago
    # Receber/Deletar produtos adicionados
    try:
        nome_add = request.POST['selectprod']
        qnt_add = request.POST['qntprod']
        newprod = Produto.objects.get(nome=nome_add)
        qs = ItensPedido.objects.filter(cod_produto=newprod.pk).filter(cod_pedido=id)

        if(qs):
            index = 0
            for p in qs:
                if(index == 0):
                    qs.update(quantidade=p.quantidade+int(qnt_add))
                    index += 1
                    if(p.quantidade<=0):
                        p.delete()
                else:
                    p.delete()
            return redirect(reverse('controle_pedidos:detalhespedido', args=(id,)), context)
        else:
            ItensPedido(cod_pedido=id, cod_produto=newprod.pk, quantidade=qnt_add).save()
            return redirect(reverse('controle_pedidos:detalhespedido', args=(id,)), context)

    except(KeyError):
        return render(request, 'controle_pedidos/detalhespedido.html', context)

def NovoPedido(request, id):
    context = {}
    # Confirmação de usuário para o Navbar
    if request.user.is_authenticated:
        context['usuariologado'] = 'Logado como: ' + request.user.get_short_name()
        if (request.user.has_perm('controle_pedidos.delete_pedido')):
            return redirect(reverse('controle_pedidos:menu', ), context)
    else:
        context['usuariologado'] = 'Deslogado'
        return redirect(reverse('controle_pedidos:login', ), context)

    context['idcomanda'] = id

    try:
        codmesa = request.POST['codigomesa']
        Pedido(cod_comanda=id, cod_mesa=codmesa).save()
        return redirect(reverse('controle_pedidos:detalhespedido', args=(id,)), context)

    except(KeyError):
        return render(request, 'controle_pedidos/novopedido.html', context)

def DetalhesGerencia(request, id):
    context = {}
    context['id'] = id

    if request.user.is_authenticated:
        context['usuariologado'] = 'Logado como: ' + request.user.get_short_name()
        if (not request.user.has_perm('controle_pedidos.delete_pedido')):
            return redirect(reverse('controle_pedidos:idcomanda', ), context)
    else:
        context['usuariologado'] = 'Deslogado'
        return redirect(reverse('controle_pedidos:login', ), context)


    # Listagem dos produtos para a tabela
    produtos = ItensPedido.objects.filter(cod_pedido=id)
    listaprodutos = []
    listavalores = []
    listaqnt = []
    for p in produtos:
        if (p.quantidade > 0):
            listaprodutos.append(Produto.objects.get(pk=p.cod_produto).nome)
            listavalores.append(Produto.objects.get(pk=p.cod_produto).valor_unitario)
            listaqnt.append(p.quantidade)

    context['lista'] = tuple(zip(*(listaprodutos, listavalores, listaqnt)))

    listatodosprods = []

    for tp in Produto.objects.all():
        listatodosprods.append(tp)

    context['TodosProdutos'] = listatodosprods
    context['mesa'] = Pedido.objects.get(cod_comanda=id).cod_mesa
    context['pago'] = Pedido.objects.get(cod_comanda=id).pago

    try:
        statuspago = request.POST['pago']

        if(statuspago == 'Já foi feito'):
            Pedido.objects.filter(cod_comanda=id).update(pago=True)

        if(statuspago == 'Ainda não foi feito'):
            Pedido.objects.filter(cod_comanda=id).update(pago=False)

        context['pago'] = Pedido.objects.get(cod_comanda=id).pago
        return render(request, 'controle_pedidos/detalhesgerencia.html', context)

    except(KeyError):
        print('erro')
        return render(request, 'controle_pedidos/detalhesgerencia.html', context)

def GerenciaProdutos(request):
    context ={}

    # Confirmação de usuário para o Navbar
    if request.user.is_authenticated:
        context['usuariologado'] = 'Logado como: ' + request.user.get_short_name()
        if (not request.user.has_perm('controle_pedidos.delete_pedido')):
            return redirect(reverse('controle_pedidos:idcomanda', ), context)
    else:
        context['usuariologado'] = 'Deslogado'
        return redirect(reverse('controle_pedidos:login', ), context)

    context['listaprodutos'] = Produto.objects.all()


    return render(request, 'controle_pedidos/gerenciaprodutos.html', context)

def AdicionarProduto(request):
    context = {}

    # Confirmação de usuário para o Navbar
    if request.user.is_authenticated:
        context['usuariologado'] = 'Logado como: ' + request.user.get_short_name()
        if (not request.user.has_perm('controle_pedidos.delete_pedido')):

controle_pedidos/templates/controle_pedidos/adicionarproduto.html
{% extends 'controle_pedidos/base.html' %}
{% block title %}Comanda Eletrônica - Menu{% endblock %}

{% block content %}
<div class="container text-center">
        <div class="col-xl-12 mx-auto">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group row">
                    <label for="nomeProduto" class="col-md-2 col-form-label">Nome do produto:</label>
                    <div class="col-md-10">
                        <input type="text" class="form-control" id="nomeProduto" name="nomeProduto" placeholder="Nome do Produto">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="valorProduto" class="col-md-2 col-form-label">Valor do produto:</label>
                    <div class="col-md-10">
                        <input type="number" step="0.01" class="form-control" id="valorProduto" name="valorProduto" placeholder="Valor do Produto">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="descricaoProduto" class="col-md-2 col-form-label">Descrição do produto:</label>
                    <div class="col-md-10">
                        <input type="text" class="form-control" id="descricaoProduto" name="descricaoProduto" placeholder="Descrição do Produto">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col">
                        <button type="submit" class="btn btn-success">Salvar</button>
                    </div>
                    <div class="col">
                        <a class="btn btn-secondary" href="{% url 'controle_pedidos:gerenciaprodutos' %}" role="button">Fechar</a>
                    </div>
                </div>
            </form>
        </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">ID de Comanda inativo!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <p>{{ erro }}</p>
      </div>
    </div>
  </div>
</div>


{% if erro %}
    <script>
    $(document).ready(function(){
    $("#myModal").modal();
  });
    </script>
{% endif %}
{% endblock %}

controle_pedidos/templates/controle_pedidos/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Controle de Comandas eletrônicas">
    <meta name="author" content="Richard Lucas">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'controle_pedidos/css/bootstrap.css' %}" >
    <!-- Bootstrap, JQuery e Popper JS -->
    <script src="{% static 'controle_pedidos/jquery-3.3.1.slim.min.js' %}" ></script>
    <script src="{% static 'controle_pedidos/popper.min.js' %}" ></script>
    <script src="{% static 'controle_pedidos/js/bootstrap.min.js' %}" ></script>

    <!-- Custom fonts for this template -->
    <link href="{% static 'controle_pedidos/theme/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'controle_pedidos/theme/vendor/simple-line-icons/css/simple-line-icons.css' %} " rel="stylesheet" type="text/css">


    <!-- Custom styles for this template -->
    <link href="{% static 'controle_pedidos/theme/css/landing-page.css' %}" rel="stylesheet">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<!-- Navigation -->
  <nav class="navbar navbar-light bg-light static-top">
    <div class="container">
        <div class="col-md">
            <a class="navbar-brand" %}">Sistema de Comandas eletrônicas</a>
        </div>
        <div class="col-md mx-auto">
            <p>{{usuariologado}}</p>
        </div>
        <div class="col-sm">
        {% if usuariologado != 'Deslogado'%}
            <a class="btn btn-danger btn-sm" href="{% url 'controle_pedidos:logout' %}">Logout</a>
        {% endif %}
        </div>
    </div>
  </nav>

{% block content %}{% endblock %}


<!-- Footer -->
  <footer class="footer bg-light">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
          <ul class="list-inline mb-2">
            <li class="list-inline-item">
              <a href="#">Sobre</a>
            </li>
            <li class="list-inline-item">&sdot;</li>
            <li class="list-inline-item">
              <a href="#">Contatos</a>
            </li>
            <li class="list-inline-item">&sdot;</li>
            <li class="list-inline-item">
              <a href="#">Termos de Uso</a>
            </li>
            <li class="list-inline-item">&sdot;</li>
            <li class="list-inline-item">
              <a href="#">Política de Privacidade</a>
            </li>
          </ul>
          <p class="text-muted small mb-4 mb-lg-0">&copy; Richard Lucas 2019. Todos os direitos reservados.</p>
        </div>
        <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
          <ul class="list-inline mb-0">
            <li class="list-inline-item mr-3">
              <a href="#">
                <i class="fab fa-facebook fa-2x fa-fw"></i>
              </a>
            </li>
            <!--<li class="list-inline-item mr-3">
              <a href="#">
                <i class="fab fa-twitter-square fa-2x fa-fw"></i>
              </a>
            </li>
            <<li class="list-inline-item">
              <a href="#">
                <i class="fab fa-instagram fa-2x fa-fw"></i>
              </a>
            </li>-->
          </ul>
        </div>
      </div>
    </div>
  </footer>
</body>
</html>

controle_pedidos/templates/controle_pedidos/cadastraratendente.html
{% extends 'controle_pedidos/base.html' %}
{% block title %}Comanda Eletrônica - Menu{% endblock %}

{% block content %}
<div class="container">
    <h2>Cadastrar novo atendente</h2>
</div>
<div class="container text-center">
        <div class="col-xl-12 mx-auto">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group row">
                    <label for="nomeCom" class="col-md-2 col-form-label">Nome do atendente:</label>
                    <div class="col-md-10">
                        <input type="text" class="form-control" id="nomeCom" name="nomeCom" placeholder="Nome do atendente">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="username" class="col-md-2 col-form-label">Nome de usuário:</label>
                    <div class="col-md-10">
                        <input type="text" class="form-control" id="username" name="username" placeholder="Nome de usuário">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="password" class="col-md-2 col-form-label">Senha:</label>
                    <div class="col-md-10">
                        <input type="password" class="form-control" id="password" name="password" placeholder="**********">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col">
                        <button type="submit" class="btn btn-success">Cadastrar</button>
                    </div>
                    <div class="col">
                        <a class="btn btn-secondary" href="{% url 'controle_pedidos:menu' %}" role="button">Fechar</a>
                    </div>
                </div>
            </form>
        </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Falha ao cadastrar.</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <p>{{ erro }}</p>
      </div>
    </div>
  </div>
</div>


{% if erro %}
    <script>
    $(document).ready(function(){
    $("#myModal").modal();
  });
    </script>
{% endif %}
{% endblock %}

controle_pedidos/templates/controle_pedidos/detalhesproduto.html
{% extends 'controle_pedidos/base.html' %}
{% block title %}Comanda Eletrônica - Menu{% endblock %}

{% block content %}
<div class="container">
    <div class="row text-center">
        <label class="col-md-2 col-form-label">Nome do produto:</label>
        <label class="col-md-10">{{ nome }}</label>
    </div>
    <div class="row text-center">
        <label class="col-md-2 col-form-label">Valor do produto:</label>
        <label class="col-md-10">{{ valor }}</label>
    </div>
    <div class="row text-center">
        <label class="col-md-2 col-form-label">Descrição do produto:</label>
        <label class="col-md-10">{{ descricao }}</label>
    </div>
    <div class="row">
        <div class="col text-center">
            <input type="button" value="Modificar" class="btn btn-primary" data-toggle="modal" data-target="#myModal"/>
        </div>
        <div class="col text-center">
            <button type="button" class="btn btn-danger" onclick="location.href='{% url 'controle_pedidos:deletarproduto' id %}'">Deletar</button>
        </div>
        <div class="col text-center">
            <a class="btn btn-secondary" href="{% url 'controle_pedidos:gerenciaprodutos' %}" role="button">Fechar</a>
        </div>
    </div>
</div>

<!-- Modal Modificar -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modificar produtos</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
          <form method="POST">
              {% csrf_token %}
              <div class="form-row">
                  <div class="form-group col-md">
                        <label for="nomeProd">Nome:</label>
                        <input type="text" class="form-control" id="nomeProd" name="nomeProd" placeholder="{{ nome }}">
                  </div>
              </div>
              <div class="form-row">
                  <div class="form-group col-md">
                      <label for="valorProd">Valor: </label>
                      <input type="number" step="0.01" id="valorProd" name="valorProd" placeholder="{{ valor }}">
                  </div>
              </div>
              <div class="form-row">
                  <div class="form-group col-md">
                        <label for="descProd">Descrição:</label>
                        <input type="text" class="form-control" id="descProd" name="descProd" placeholder="{{ descricao }}">
                  </div>
              </div>
              <div class="modal-footer">
                  <button type="submit" class="btn btn-success">Modificar</button>
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
              </div>
          </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

controle_pedidos/templates/controle_pedidos/gerenciaprodutos.html
{% extends 'controle_pedidos/base.html' %}
{% block title %}Comanda Eletrônica - Menu{% endblock %}

{% block content %}
<div class="container">
    <div class="list-group">
        <div class="row md-4">
            <div class="col-4"></div>
            <div class="col-md-4 text-center">
                {% for prod in listaprodutos %}
                    <a href="{% url 'controle_pedidos:detalhesproduto' prod.pk %}" class="list-group-item list-group-item-action">{{prod.nome}}</a>
                {% endfor %}
            </div>
                <div class="col-4"></div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col text-center">
            <a class="btn btn-primary btn-md mx-auto" role="button" href="{% url 'controle_pedidos:adicionarproduto' %}">Adicionar</a>
        </div>
        <div class="col text-center">
            <a class="btn btn-secondary btn-md" role="button" href="{% url 'controle_pedidos:menu' %}">Fechar</a>
        </div>
    </div>
</div>

{% endblock %}

controle_pedidos/templates/controle_pedidos/idcomanda.html
{% extends 'controle_pedidos/base.html' %}
{% block title %}Gerenciamento de Comandas{% endblock %}

{% block content %}
<div class="container">
    <div class="row text-center">
        <p class="h2 text-center mb-5"><strong>Pesquisar ID da Comanda</strong></p>
    </div>
</div>

<div class="container text-center">
        <div class="col-xl-12 mx-auto">
            <form method="POST">
                {% csrf_token %}
                <div class="form-inline">
                    <div class="row mb-4">
                        <div class="col-md mx-auto">
                            <label>ID da Comanda: </label>
                        </div>
                        <div class="col-md">
                            <input type="text" class="form-control" name="idcomanda" placeholder="ID da Comanda">
                        </div>
                        {% if perm == 'True' %}
                        <div class="col-md">
                            <a role="button" class="btn btn-primary" href="{% url 'controle_pedidos:listapedidos' %}">Ver lista de pedidos</a>
                        </div>
                        {% endif %}
                    </div>
                    <div class="w-100"></div>
                    <div class="row">
                        <div class="col-md mx-auto">
                            <input type="submit" class="btn btn-primary" value="Confirmar">
                        </div>
                        {% if perm == 'True' %}
                        <div class="col-md mx-auto">
                            <a class="btn btn-secondary" href="{% url 'controle_pedidos:menu' %}">Voltar</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </form>
        </div>
</div>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">ID de Comanda inativo!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <p>{{ erro }}</p>
          {% if perm != 'True' %}
            <p>Você pode adicionar uma nova comanda aqui:</p>
                <div class="modal-footer">
                    <a type="button" class="btn btn-success" href="novopedido/{{ idpedido }}">Adicionar</a>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                </div>
          {% endif %}
      </div>
        {% if perm == 'True' %}
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
            </div>
        {% endif %}
    </div>
  </div>
</div>


{% if erro %}
    <script>
    $(document).ready(function(){
    $("#myModal").modal();
  });
    </script>
{% endif %}

{% endblock %}

controle_pedidos/templates/controle_pedidos/menu.html
{% extends 'controle_pedidos/base.html' %}
{% block title %}Comanda Eletrônica - Menu{% endblock %}

{% block content %}
<div class="container">
    <div class="jumbotron">
      <h1 class="display-4">Bem-vindo, gerente!</h1>
      <p class="lead">A partir daqui, acesse as páginas de gerenciamento do Sistema de Comanda Eletrônica</p>
      <hr class="my-4">
      <p>Acesse a partir daqui o gerenciamento de produtos disponíveis e a lista de pedidos ativos</p>
      <a class="btn btn-primary btn-lg mb-4" href="{% url 'controle_pedidos:idcomanda' %}" role="button">Lista de pedidos ativos</a>
      <a class="btn btn-primary btn-lg mb-4" href="{% url 'controle_pedidos:gerenciaprodutos' %}" role="button">Gerenciamento de Produtos</a>
      <a class="btn btn-primary btn-lg mb-4" href="{% url 'controle_pedidos:cadastraratendente' %}" role="button">Cadastrar novo atendente</a>
    </div>
</div>
{% endblock %}